
examination_list = {
    # LABORATORY-------------
    "EXM_BACTERIA_CULTIVATION_SAMPLING": [
        'SYM_BRONCHIAL_INFECTION',
        'SYM_S._PYOGENES_PRESENT'
    ],
    "EXM_BLOOD_TEST": [
        "SYM_CRP_HIGH",
        "SYM_SEPTIC_SHOCK",
        "SYM_HISTOPLASMA_DETECTED",
        "SYM_HAPTOGLOBIN_HIGH",
        "SYM_THROMBOCYTOPENIA_DETECTED",
        "SYM_CLOTTING_FACTOR_LOW",
        "SYM_THALASSEMIA_DISCOVERED",
        "SYM_HYPERLIPIDEMIA",
        "SYM_HIGH_SUGAR_LEVEL",
    ],
    "EXM_EXECRETIONS_TEST": [
        "SYM_HEMATOCHEZIA",
        "SYM_DARK_URINE",
        "SYM_HEMATURIA",
        "SYM_HEMATOCHEZIA",
        "SYM_PORK_TAPEWORM_PRESENT",
        "SYM_BEEF_TAPEWORM_PRESENT",
        "SYM_PROTEINURIA"
    ],

    # DOCTOR----------------
    "EXM_INTERVIEW": [
        "SYM_CHILLS",
        "SYM_NAUSEA",
        "SYM_VOMITING",
        "SYM_DIARRHEA",
        "SYM_HEADACHE",
        "SYM_ABDOMINAL_CRAMPS",
        "SYM_ABDOMINAL_PAIN",
        "SYM_FATIGUE",
        "SYM_EXCESSIVE_BURPING",
        "SYM_FLATULENCE",
        "SYM_WEIGHT_LOSS",
        "SYM_HEMOPTYSIS",
        "SYM_WEAKNESS",
        "SYM_NIGHT_SWEATS",
        "SYM_LOSS_OF_APPETITE",
        "SYM_MUSCLES_AND_JOINTS_PAIN",
        "SYM_DIZZINESS",
        "SYM_PHOTOPHOBIA",
        "SYM_POLYURIA",
        "SYM_HUNGER",
        "SYM_THIRST",
        "SYM_RINGING_IN_THE_EARS",
        "SYM_HEARING_DIFFICULTIES",
        "SYM_DIARRHEA",
        "SYM_DIMINISHED_HEARING",
        "SYM_ITCHY_BLISTERS",
        "SYM_BLOATING",
        "SYM_PAPULAS_AND_VESICLES",
        "SYM_SWALLOW_PAIN",
        "SYM_SNEEZING",
        "SYM_RASH",
        "SYM_BACK_PAIN",
        "SYM_SLEEPING_DIFFICULTIES",
    ],
    "EXM_TEMPERATURE_MEASUREMENT": [
        'SYM_FEVER'
    ],
    "EXM_NASAL_CAVITY_INSPECTION": [
        'SYM_NASAL_CONGESTION'
    ],
    "EXM_ORAL_CAVITY_INSPECTION": [
        "SYM_SORE_THROAT",
        "SYM_RED_SWOLLEN_TONSILS",
        "SYM_HOARSENESS",
        "SYM_WHITE_PATCHES_ON_TONSILS",
    ],
    "EXM_NECK_PALPATION": [
        "SYM_SWOLLEN_LYMPH_NODES",
        "SYM_DYSPHAGIA",
        "SYM_SWALLOW_PAIN",
        "SYM_PAINFUL_CERVICAL_LYMPH_NODES"
    ],
    "EXM_ABDOMINAL_PALPATION": [
        "SYM_ABDOMINAL_SWELLING",
    ],
    "EXM_AUSCULTATION": [
        "SYM_SPUTUM_COUGH",
        "SYM_DRY_COUGH",
        "SYM_IRRITABLE_COUGH",
        "SYM_BREATHING_DIFFICULTIES",
        "SYM_WHEEZING"
    ],
    "EXM_BLOOD_PRESSURE": [
        "SYM_HYPOTENSION",
        "SYM_HYPOVOLEMIC_SHOCK"
    ],
    "EXM_VISUAL_TEST": [
        "SYM_LOSS_OF_VISION",
        "SYM_BLURRED_VISION"
    ]
}